place = ['Jiuzhai_Valley','Mount_Tai','the_Great_Wall','Sanya','Bird-Nest']
print(place)
print(sorted(place))
print(place)
print(sorted(place,reverse=True))
print(place)
place.reverse()
print(place)
place.reverse()
print(place)
place.sort()
print(place)
place.sort(reverse=True)
print(place)
