number = range(1,10)
numbers = list(number)
print(numbers)
print('The first three items in the list are:'+str(numbers[:3]))
print('Three items from the middle of the list are:'+str(numbers[3:6]))
print('The last three items in the list are:'+str(numbers[-3:]))
