str1 = 'wdnmd'
str2 = 'WdnMd'
print('str1 == str2 ?')
print(str1 == str2)
print('str1  == str2.lower() ?')
print(str1  == str2.lower())
print('5 == 5 ?')
print(5 == 5)
print('5 == 3 ?')
print(5 == 3)
print('5 != 3 ?')
print(5 != 3)
print('5 > 3 ?')
print(5 > 3)
print('5 < 3 ?')
print(5 < 3)
print('5 >= 5 ?')
print(5 >= 5)
print('5 <= 5 ?')
print(5 <= 5)
print('5 >= 6 ?')
print(5 >= 6)
print('5 <= 6 ?')
print(5 <= 6)
print('5 > 6) and (5 > 3) ?')
print((5 > 6) and (5 > 3))
print('(5 > 6) or (5 > 3) ?')
print((5 > 6) or (5 > 3))
numbers = [2,4,7,8]
print('numbers'+str(numbers))
print('Is "2" in numbers ?')
print(2 in numbers)
print('Is "5" in numbers ?')
print(5 in numbers)
print('Is 6 not in numbers ?')
print(6 not in numbers)
print('Is "4" not in nujbers')
print(4 not in numbers)
